#!/bin/bash

create_dirs() {
  mkdir -p $(cat ./setup/Dirsfile|grep -v "#");
}

install_homebrew() {
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)";
}

install_brewDeps() {
  brew update;
  brew upgrade;
  brew install $(cat ./setup/Brewfile|grep -v "#");
  brew cleanup;
}

install_caskDeps() {
  install caskroom/cask/brew-cask;
  brew tap caskroom/versions;
  brew cask install $(cat ./setup/Caskfile|grep -v "#");
}

install_languages() {
  curl -sSL https://get.rvm.io | bash -s stable;
  ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)";
  bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer);
}

configure_osx() {
  source ./setup/osx.sh;
  source ./setup/git.sh;
}

link_dotfiles() {
  source ./setup/link.sh
}

start_zsh() {
  zsh;
}

main() {
  create_dirs;
  install_homebrew;
  install_brewDeps;
  install_caskDeps;
  install_languages;
  configure_osx;
  link_dotfiles;
  start_zsh;
}

main;
