#!/bin/bash

setup_admin() {
  # Ask for the administrator password upfront
  sudo -v
  # Keep-alive: update existing `sudo` time stamp until `.osx` has finished
  while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
}

create_dirs() {
  mkdir -p $(cat ./setup/Dirsfile|grep -v "#")
}

install_homebrew() {
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
}

install_brewDeps() {
  brew update
  brew upgrade
  brew install $(cat ./setup/Brewfile|grep -v "#")
  brew cleanup
}

install_caskDeps() {
  install caskroom/cask/brew-cask
  brew tap caskroom/versions
  brew cask install $(cat ./setup/Caskfile|grep -v "#")
}

install_languages() {
  curl -sSL https://get.rvm.io | bash -s stable
  nvm install 0.10
  nvm install 0.11
  nvm alias default 0.10
}

configure_osx() {
  source ./setup/osx.sh
  source ./setup/git.sh
}

link_dotfiles() {
  source ./setup/link.sh
}

configure_zsh() {
  curl -L http://install.ohmyz.sh | sh
  chsh -s /bin/zsh
  rm ~/.zshrc
}

main() {
  setup_admin
  create_dirs
  install_homebrew
  install_brewDeps
  install_caskDeps
  install_languages
  configure_osx
  configure_zsh
  link_dotfiles
}

main
