#!/bin/sh

mkdir -p ~/src/yw
cd "$HOME/src/yw" || exit

git clone yoshuawuyts/knowledge
git clone yoshuawuyts/talks
git clone yoshuawuyts/passwords

ln -s "$(pwd)/passwords" "$HOME/.password-store"

# config npm
npm config set init.author.name "Yoshua Wuyts"
npm config set init.author.email "yoshuawuyts@gmail.com"
npm config set init.author.github "yoshuawuyts"
