#!/bin/bash
#
# bootstrap installs things.

DOTFILES_ROOT=$(pwd)

set -e
echo ''

fail () {
  printf "%s\n" "$1" && exit
}

setup_gitconfig () {
  if ! [ -f git/gitconfig.symlink ]; then
    echo 'setup gitconfig'

    echo ' - What is your github author name?'
    read -e git_authorname
    echo ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" git/gitconfig.symlink.example > git/gitconfig.symlink

    echo 'gitconfig'
  fi
}

link_files () {
  ln -s "$1" "$2"
  echo "linked $1 to $2"
}

install_dotfiles () {
  echo 'installing dotfiles'

  overwrite_all=false
  backup_all=false
  skip_all=false

  for source in $(find "$DOTFILES_ROOT" -maxdepth 2 -name \*.symlink)
  do
    dest="$HOME/.$(basename \"${source%.*}\")"

    if [ -f "$dest" ] || [ -d "$dest" ]
    then

      overwrite=false
      backup=false
      skip=false

      if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
      then
        echo "File already exists: $(basename "$source"),"
        echo "what do you want to do?"
        echo "[s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o ) overwrite=true;;
          O ) overwrite_all=true;;
          b ) backup=true;;
          B ) backup_all=true;;
          s ) skip=true;;
          S ) skip_all=true;;
          * ) ;;
        esac
      fi

      if [ "$overwrite" == "true" ] || [ "$overwrite_all" == "true" ]
      then
        rm -rf "$dest"
        echo "removed $dest"
      fi

      if [ "$backup" == "true" ] || [ "$backup_all" == "true" ]
      then
        mv "$dest" "$dest"\.backup
        echo "moved $dest to $dest.backup"
      fi

      if [ "$skip" == "false" ] && [ "$skip_all" == "false" ]
      then
        link_files "$source" "$dest"
      else
        echo "skipped $source"
      fi

    else
      link_files "$source" "$dest"
    fi

  done
}

setup_gitconfig
install_dotfiles

# If we are on a mac, lets install and setup homebrew
if [ "$(uname -s)" == "Darwin" ]
then
  echo "installing dependencies"
  if . bin/dotc > /tmp/dotfiles-dot 2>&1
  then
    echo "dependencies installed"
  else
    fail "error installing dependencies"
  fi
fi

echo ''
echo '  All installed!'
