#!/bin/sh

set -e

# nvim expects to live in ~/.config/nvim
rm -rf "$HOME/.config/nvim"
mkdir -p "$HOME/.config"
ln -s "$HOME/.vim" "$HOME/.config/nvim"

# install python extensions for nvim
sudo pip2 install neovim

# get vim plug so plugins can be installed
curl -fLo ~/.config/nvim/autoload/plug.vim \
  --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# install all the plugins
vim +PluginInstall +qall

# install YCM plugins
# https://github.com/Valloric/YouCompleteMe#mac-os-x
cd ~/.config/nvim/plugged/YouCompleteMe
./install.py --clang-completer

# rust completion
cargo install racer
