#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
[ -f $sysresources ] && xrdb -merge $sysresources
[ -f $sysmodmap ] && xmodmap $sysmodmap
[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Make caps work as ctrl/esc
setxkbmap -option 'caps:ctrl_modifier' && xcape -e 'Caps_Lock=Escape' &
setxkbmap -option 'escape:alupckeys' & # remap escape to tilde / accent grave

# Prevent touchpad from jumping around
syndaemon -i 0.5 -t -k -R -d

# Enable redshift
redshift &

# Enable middle scroller to work
xinput set-prop "TPPS/2 IBM TrackPoint" "libinput Scroll Method Enabled" 0 0 1

# Set background color
xsetroot -solid "#2d2d2d"

twm &
xclock -geometry 50x50-1+1 &
xterm -geometry 80x50+494+51 &
xterm -geometry 80x20+494-0 &
xset r rate 250 60 # set key repeat speed

# Initialize i3
(sleep 6; notify-critical) &
(sleep 3; polybar top) &
(sleep 6; workrave) &
(sleep 6; power-warn) &
(sleep 1; feh --bg-scale ~/Code/yw/dotfiles/feh/xp.jpg) &
exec i3
