#!/bin/bash

main() {
  if [ -z "$1" ]; then
    echo "$1"
    printf 'Usage: c <user/repo>\n'
    exit 1
  fi

  uri="$(clean_uri "$1")"
  user="$(echo "$uri" | sed 's|/.*||')"
  repo="$(echo "$uri" | sed 's|.*/||')"

  if [ "$user" = "yw" ]; then
    user="yoshuawuyts"
  fi

  if [ -z "$PROJECTS" ]; then
    printf 'PROJECTS env var was not set, exiting\n'
    exit 1
  fi

  projectdir="$PROJECTS/$uri"
  userdir="$PROJECTS/$user"

  if [ -d "$projectdir" ]; then
    boot_project
  else
    clone_project
    return $?
  fi
}

clean_uri() {
  echo "$1" \
    | sed 's|^https://github.com/||' \
    | tr '/' ' ' \
    | awk '{print $1 "/" $2}'
}

boot_project() {
  pushd "$projectdir" || return 1
  if [ -z "$TMUX" ]; then mx; fi
}

clone_project() {
  if [ ! -d "$userdir" ]; then
    mkdir "$userdir"
  fi
  pushd "$userdir" || exit 1
  hub clone "$user/$repo"
  if [ $? -ne 0 ]; then
    printf 'zsh/c: git clone failed. Exiting\n'
    return 1
  fi
  boot_project
}

main "$@"
