# Make sure we’re using the latest Homebrew

# GNU core utilities (those that come with OS X are outdated)
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
coreutils
moreutils
findutils

# wget with IRI support
wget --enable-iri

# more recent versions of some OS X tools
vim --override-system-vi
homebrew/dupes/grep
homebrew/dupes/screen

# other useful binaries
ack
autoconf
autojump
automake
bash
bison
boost
brew-cask
bsdmake
cairo
cloog
cowsay
dirmngr
docker
fontconfig
freetype
gcc
gdbm
gettext
git
git-extras
glib
glide
gmp
gnu-getopt
gnupg2
go
gpg-agent
htop-osx
httpie
httpry
hub
imagemagick --with-webp
isl
jpeg
jq
libassuan
libffi
libgcrypt
libgpg-error
libidn
libksba
libmpc
libpng
libtool
libusb
libusb-compat
libyaml
links
lynx
makedepend
mercurial
mpfr
nvm
openssl
pass
pcre
pinentry
pixman
pkg-config
pth
pwgen
python
readline
rename
rust
sqlite
ssh-copy-id
stow
tcpflow
tree
webp
xz
zsh

homebrew/binary/packer
