# Make sure we’re using the latest Homebrew

# GNU core utilities (those that come with OS X are outdated)
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
coreutils
moreutils
findutils

# wget with IRI support
wget --enable-iri

# more recent versions of some OS X tools
vim --override-system-vi
homebrew/dupes/grep
homebrew/dupes/screen

# other useful binaries
brew-cask
coreutils
docker
gettext
go
htop-osx
httpie
hub
imagemagick --with-webp
libtool
lynx
nvm
openssl
python
rename
sqlite
wget
zsh
consul
riak
nsq
jq
redis
postresql
xz
cowthink
mercurial

homebrew/binary/packer
homebrew/versions/lua52
