# Fix locale
export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export GPG_TTY=$(tty)

export MANPATH="/usr/share/bcc/man/man8:$MANPATH"
export PATH="/usr/share/bcc/tools:$PATH"

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# colors for later use
clr_reset="$(tput sgr0)"
clr_red="$(tput setaf 1)"
clr_blue="$(tput setaf 4)"
clr_cyan="$(tput setaf 6)"
clr_white="$(tput setaf 7)"

# command prompt
prompt_command () {
  if [ $? -eq 0 ]; then local clr_status="$clr_white"
  else local clr_status="$clr_red"; fi

  if [ $USER = root ]; then local sign="#"
  else local sign="$"; fi

  local timestamp="$(date +'%H:%M:%S')"
  local top="$timestamp \u@\H"
  local prompt="$clr_blue[\w]$clr_reset $clr_status$sign$clr_reset"

  PS1="$(printf "\n\r%s\n%s " "$top" "$prompt")"
}
PROMPT_COMMAND=prompt_command

# vim mode
set -o vi

# Global config
export EDITOR=vim
export VISUAL=vim
export PAGER=less
export PROJECTS="$HOME/Code"
export TEMPLATES="$PROJECTS/yw/templates"

# Fix application chrome
GDK_DPI_SCALE=1.4

# Aliases
alias git='hub'
alias g='git'
alias gh='hub browse'
alias ls='ls --color=auto --group-directories-first'
alias ll='ls -alph --color=auto --group-directories-first'
alias s='git status --short'

# Node
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# Enable SSH
export SSH_AUTH_SOCK="$XDG_RUNTIME_DIR/ssh-agent.socket"

# Start X if it's not started yet
if [ -z "$DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ]; then
  exec startx
fi

# Enable autocompletion
if [ -f /etc/bash_completion ]; then
  /etc/bash_completion
fi

_complete_c () {
  local cur_word="${COMP_WORDS[COMP_CWORD]}"
  local files="$(ls "$PROJECTS/$cur_word")"
  COMPREPLY="$(compgen -W "$files")"
}
complete -F _complete_c c
